# Example configuration
par_config:
  par_isotope: 'monoisotopic'             # Type of molecular mass
  par_ionization: 'ESI'                   # Ionization type
  par_col_type: 'Q'                       # Collision type
  par_ce_unit: 'V'                        # Unit for collision energy
  par_instrument: 'TripleTOF 5600 SCIEX'  # Instrument name
  par_instrument_type: 'LC-ESI-QTOF '     # Instrument type
  par_data_source: 'bfg'                  # Data source identifier (needs to be whitelisted in config.py)
  par_authors: 'Björn Ehlig; Kevin S. Jewell; Ole Lessmann; Arne Wick'  # Author name(s)
  par_affiliation: 'Federal Institute of Hydrology (Bundesanstalt für Gewässerkunde), Koblenz, Germany'  # Author affiliation

# Special adduct notation rules (leave curly brackets empty if no special cases needed).
adduct_notation: {
  'cation': '[M]+',
  'Ethylamin': '[M+C2H7N+H]+',
  'FA': '[M+HCOO-]-',
  'NaFA': '[M+NaCOO-]-',
}
